source 'https://rubygems.org'

gem 'activesupport', '4.2.7'
gem 'slack-ruby-client'
gem 'sqlite3'
gem 'activerecord'
gem 'octokit'
gem 'haml'
gem 'json'
gem 'time_difference'
gem 'sinatra'
gem 'standalone_migrations'
gem 'rake', '10.0.0'
